[feature] list product and delete product
thanhit23/rose-petals-admin pull request #11
Opened 2022-11-13 08:38 UTC by thanhit23

2022-11-13 09:44 UTC, tannguyenit requested changes

2022-11-13 09:44 UTC, tannguyenit commented on src/containers/Products/Add/index.js
> +  key: 'category',
product mà ịnect cái category ???

2022-11-13 09:44 UTC, tannguyenit commented on src/containers/Products/Add/index.js
> +const withSagaCategory = injectSaga({ key: 'category', saga: sagaCategory });
category ???

2022-11-13 09:44 UTC, tannguyenit commented on src/containers/Products/Add/saga.js
> +    callback();
nếu có callback và callback nó là 1 function thì mới call, viết mà k check kiểu này có ngày bị lỗi

2022-11-13 09:44 UTC, tannguyenit commented on src/containers/Products/List/saga.js
> +    yield put({ type: GET_PRODUCTS_REQUEST });
delete success rồi put action request làm gì nữa à

2022-11-14 14:27 UTC, thanhit23 commented on src/containers/Products/List/saga.js
> +    yield put({ type: GET_PRODUCTS_REQUEST });
put action cho nó get lại data

2022-11-14 14:42 UTC, tannguyenit requested changes

2022-11-14 14:42 UTC, tannguyenit commented on src/components/Products/List/index.js
> +          {Object.keys(meta).length ? table : <p>empty</p>}
chỗ ni chưa sửa lại theo cách mới

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Categories/List/reducers.js
> +        draft.list.data = [];
chỗ ni hôm bữa test thôi, giờ back lại như cũ cho nó đúng chứ

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Products/Add/actions.js
> +export const getCategories = () => ({
getAllCategories
Nó nên liên quan đến cái key , body thể hiện 1 ý nghĩa, cái tên function thì 1 ý nghĩa khác

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Products/Add/actions.js
> +export const getCategoriesSuccess = data => ({
tương tự cái trên

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Products/Add/actions.js
> +export const getCategoriesFailed = message => ({
tương tự cái trên

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Products/Add/index.js
> +const withSaga = injectSaga({ key: 'addProduct', saga });
saga có cần phải là addProduct hay ko, nếu dùng product thì có ảnh hưởng chi ko

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Products/List/saga.js
> +    yield put({ type: GET_PRODUCTS_REQUEST });
tại sao cần put action cho nó get lại data mà ko back nó về component list, rồi chính cái thèn component đó sẽ làm công việc của nó , dùng callback á

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Table/index.js
> +  function optionSelect(cell) {
cách viết function ko thống nhất

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Table/index.js
> +                  if (cell.column.id === selectOption) {
về cơ bản chỗ ni nó sai, là đang viết logic của 1 cái cụ thể vô 1 component dùng chung

2022-11-14 14:42 UTC, tannguyenit commented on src/containers/Users/Edit/saga.js
> +  if (!res) callback();
nếu callback ko phải là function mà call kiểu này thì toang

2022-11-14 15:11 UTC, thanhit23 commented on src/containers/Table/index.js
> +  function optionSelect(cell) {
về cái yield put({ type: GET_PRODUCTS_REQUEST }); thì hiện tại mình đang ở page list thì chuyển đi đâu nữa, dù có chuyển thì cx hông đc

2022-11-14 15:14 UTC, thanhit23 commented on src/containers/Table/index.js
> +                  if (cell.column.id === selectOption) {
chứ chưa suy nghĩ ra cách xử lý nên mới làm thế

2022-11-17 03:22 UTC, merged