[Feature] complete upload file
thanhit23/rose-petals-admin pull request #17
Opened 2022-12-10 04:10 UTC by thanhit23

2022-12-10 05:30 UTC, tannguyenit approved these changes

2022-12-10 05:30 UTC, tannguyenit commented on src/components/Products/Add/index.js
> +            {uploadFile}
chỗ này nên đặt là renderUploadComponent cho nó rõ nghĩa , Nhưng cả có xem cái dưới rồi, cái component mà chỉ có mỗi cái input thì cũng k có ý nghĩa mấy

2022-12-10 05:30 UTC, tannguyenit commented on src/components/Products/List/index.js
> +              className="object-contain h-[100px] w-[100px]"
chỗ ni là cái nên viết thành 1 cái compoenet nè, lý do là nó dính vô cái env, nêu sau này đổi env 1 phát là đi sửa nhiều nơi 
Nhưng cảm giác hơi sai sai , đúng thì lúc này đã có cái url từ phía API rồi

2022-12-10 05:30 UTC, tannguyenit commented on src/components/UploadFile/index.js
> +  return (
1 component mà chỉ có cái này thì đâu có ý nghĩa chi nhiều đâu

2022-12-10 05:30 UTC, tannguyenit commented on src/containers/Products/Add/index.js
> +    addProduct({ ...data, images: [] }, file, callback);
chỗ này sao khó hiểu z, vừa có file, vừa có data rồi có payload

2022-12-10 05:30 UTC, tannguyenit commented on src/containers/Products/Add/saga.js
> +  yield takeEvery(ADD_PRODUCT_REQUEST, uploadFile);
add product request mà function name lại là uploadFile , tên và chức năng k liên quan gì luôn

2022-12-10 05:30 UTC, tannguyenit commented on src/service/constants.js
> +export const ERROR_SERVER = 500;
SERVER_ERROR

2022-12-10 05:30 UTC, tannguyenit commented on src/service/index.js
> +        store.dispatch({ type: LOGOUT_REQUEST });
SERVER_ERROR là lỗi từ phía server mà sao phải logout 
------------
Logout chỉ xảy ra khi status trả về là 401 thôi

2022-12-10 05:30 UTC, tannguyenit commented on src/service/index.js
> +  post = (url, body, config) => this.instance.post(url, body, config);
giờ thêm mới 1 param là config, vậy ở mấy cái nơi gọi cũ k thêm params thì nó lỗi sao ?????????

Ví dụ trước đây:
```
Service.post('xxx', {})
```
thì bây giờ phải thêm 1 params nữa, k thêm nó báo lỗi sao

2022-12-10 05:30 UTC, tannguyenit commented on src/service/index.js
> -  setHeader = token => {
```
import {map} from 'lodash';

setHeaderDefault = headers => {
    map(headers, (key, value) => {
        this.instance.defaults.headers.common[key] = value;
    })
}
setBearerToken = token => this.setHeaderDefault({Authorization: `Bearer ${token}`})
```
Ex:

```
Service.setBearerToken('token');
---

Service.setHeaderDefault({
    'Content-Type': 'multipart/form-data',
});
```

2022-12-10 05:30 UTC, tannguyenit commented on src/service/index.js
> -  setHeader = token => {
```
Service.setHeaderDefault({
    'Content-Type': 'multipart/form-data',
});
```
Đây là ví dụ, còn áp dụng cho cái file thì k nên, có nghĩa là nếu set default thì các request sau đó nó luôn luôn có cái key này, nên mới để tên function là setHeaderDefault

2022-12-10 05:30 UTC, tannguyenit commented on src/service/index.js
> +  post = (url, body, config) => this.instance.post(url, body, config);
Solution:
```
post = (url, body, config = {}) => this.instance.post(url, body, config);
```

2022-12-10 06:34 UTC, thanhit23 commented on src/components/UploadFile/index.js
> +  return (
thế h k tách thành component hay sao

2022-12-10 06:36 UTC, thanhit23 commented on src/containers/Products/Add/index.js
> +    addProduct({ ...data, images: [] }, file, callback);
thì truyền thêm thèn file vô
để xử lý thèn file trc rồi add product

2022-12-11 03:52 UTC, tannguyenit requested changes

2022-12-11 03:52 UTC, tannguyenit commented on src/containers/LoginPage/service.js
> +  Service.setBearerToken('/admin/auth/login', token);
setToken thì liên quan gì cái `'/admin/auth/login'`

2022-12-11 03:52 UTC, tannguyenit commented on src/containers/UploadFile/service.js
> +export const setContent = () =>
setHeaderContent

2022-12-11 03:52 UTC, tannguyenit commented on src/containers/UploadFile/service.js
> +  Service.setHeaderDefault({
haiz, noí chỗ ni rồi mà, ví dụ sau khi set xong, thì check mấy cái API sau đó, xem cái Content-Type nó là gì, nếu là `multipart/form-data` thì nó sai

2022-12-11 03:52 UTC, tannguyenit commented on src/service/index.js
> +        window.location.reload();
ko reload chi hết , báo lỗi thôi

2022-12-11 04:07 UTC, thanhit23 commented on src/containers/UploadFile/service.js
> +  Service.setHeaderDefault({
cái ni bin check rồi mấy cái API sau đó nó k phải là `multipart/form-data`

2022-12-12 08:16 UTC, merged