[Feature] complete list orders
thanhit23/rose-petals-admin pull request #26
Opened 2022-12-30 12:54 UTC by thanhit23

2022-12-31 14:55 UTC, tannguyenit requested changes

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Orders/Edit/index.js
> +import { STATUS } from './constants';
chỗ ni cả nghĩ lại rồi, k cần phải defined ra constant đâu, status nó là field name nên k phù hợp để defined

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Orders/Edit/index.js
> +  const arrStatus = ['cancelled', 'pending', 'processing', 'delivered'];
Cái ni là cái cần defined ra constant nè

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Orders/List/index.js
> +  const arrStatus = ['cancelled', 'pending', 'processing', 'delivered'];
constant

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Orders/List/index.js
> +          'text-[#4e97fd] bg-[#dbf0fe] rounded-lg': status === 1,
chỗ này thấy nó cấn cấn sao á, k smooth lắm 
```
color = [
'text-[#e94560] bg-[#ffeaea]',
'text-[#4e97fd] bg-[#dbf0fe] rounded-lg'
....
]
```

```
clx(color[status], 'inline-flex text-xs py-1 px-4')
```
nhuw này ổn hơn ko và có work ko ( check thử )

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Orders/List/index.js
> +      Header: 'Name User',
User name chứ k phải là name user

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Orders/List/index.js
> +    if (searchValue) setValueSearch(searchValue);
viết if như thế thì viết sang kiểu ni luôn 
```
    searchValue && setValueSearch(searchValue);
```

2022-12-31 14:55 UTC, tannguyenit commented on src/components/Table/index.js
> +      {!data.length && <tr className="h-40" />}
Thông thường nếu ko có thì sẽ render ra 1 cái text là no record 
Giống như này 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/24540921/210140595-9a3c2884-dc14-4aba-87e3-7b1207a8c0a0.png">

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/LoginPage/actions.js
> +  type: FETCH_LOGIN_FAILED,
sai về tên key:
FETCH là dùng cho method GET 
ở đây login là POST thì k thể dùng từ FETCH

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/LoginPage/actions.js
> +  type: FETCH_LOGIN_FAILED,
Nếu muốn dùng prefix thì có thể dùng SUBMIT_XXXX

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/LoginPage/actions.js
> +  type: FETCH_LOGIN_FAILED,
hoặc đơn giản chỉ cần
* LOGIN_REQUEST
* LOGIN_SUCCESS
* LOGIN_FAILED

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/Orders/Edit/actions.js
> +  GET_ORDER_FAILED,
Thống nhất lại 1 kiểu đi, lúc thì GET_XXX lúc thì FETCH_XXXX

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/Orders/Edit/actions.js
> +  type: DELETE_ORDER_DATA_EDIT,
DELETE_ORDER_DATA_EDIT
trong 1 cái text lại có 2 động từ, DELETE rổi EDIT 
dịch ra là đã thấy sai rồi 
 DELETE_ORDER ( nó ko quan tâm là order đó edit hay là ở đâu hết )

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/Orders/List/constants.js
> +export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST';
DELETE_ORDERS , ở đây xoá 1 hay xoá nhiều, nêu xoá 1 item thì cái chữ S trong ORDER nó sai 
------------
Họ đọc vô cái text là họ có thể hiểu được API nó như nào, cả đang hiểu là 1 lúc có thể xoá nhiều order

2022-12-31 14:55 UTC, tannguyenit commented on src/containers/Orders/List/reducers.js
> +import { GET_ORDER_SUCCESS, DELETE_ORDER_DATA_EDIT } from '../Edit/constants';
GET_ORDER_SUCCESS
ở đây nên là ORDER`S`

2023-01-02 05:52 UTC, tannguyenit requested changes

2023-01-02 05:52 UTC, tannguyenit commented on src/containers/Orders/Edit/actions.js
> +  type: DELETE_ORDER_DATA_OLD,
chi ri ?????

2023-01-02 05:52 UTC, tannguyenit commented on src/containers/Orders/Edit/actions.js
> +  type: DELETE_ORDER_DATA_OLD,
gì mà old với new

2023-01-02 05:52 UTC, tannguyenit commented on src/containers/Orders/Edit/constants.js
> +export const DELETE_ORDER_DATA_OLD = 'DELETE_ORDER_DATA_OLD';
sao có vụ old ở đây, handle cho case nào

2023-01-02 05:52 UTC, tannguyenit commented on src/containers/Orders/List/actions.js
> +  type: GET_ORDERS_REQUEST_TABLE,
sao có chữ TABLE ở đây nữa

2023-01-02 14:06 UTC, thanhit23 commented on src/containers/Orders/List/actions.js
> +  type: GET_ORDERS_REQUEST_TABLE,
để nó show loading trong table

2023-01-03 01:46 UTC, merged